# Generated by Django 2.1.4 on 2019-02-07 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='listing',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='listing_id',
            new_name='item_id',
        ),
    ]
